sudo: false
os:
- linux
- osx
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_retry curl -L "https://get.haskellstack.org/stable/linux-x86_64.tar.gz" | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_retry curl -L "https://get.haskellstack.org/stable/osx-x86_64.tar.gz" | tar xz -C ~/.local/bin '*/stack'; mv ~/.local/bin/stack-*/stack ~/.local/bin/stack;
  fi
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal install --haddock --no-haddock-deps
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_retry curl -L "https://github.com/tfausak/github-release/releases/download/1.2.2/github-release-linux.gz" | zcat -d > ~/.local/bin/github-release; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_retry curl -L "https://github.com/tfausak/github-release/releases/download/1.2.2/github-release-osx.gz" | zcat -d > ~/.local/bin/github-release; fi
deploy:
  provider: script
  script: bash scripts/deploy.sh "${TRAVIS_OS_NAME}" "${TRAVIS_TAG}"
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: PPjcOuWp3/X/qpPHoQUZ34iegI5zrUmb7mscZqp9Gva36OoZagDDkjZqHaOf9/0vaA8e/QGGVHNAbg2zCrGVJS540jBJ59RsYBZOpEyzYOpLSNm4DWj3pNiwiVV9aC7n8cvvCTnxHG0xf0AKz5pNNRMxvXCXlDvpbclBgAybqkfeD2bH6tfdFJAGT8stsz8+UcMFpee725rfSEPhdvJCDFiWAtIX7cfsHw2H/ChhGPuFtg91YYJchMFGyTesOuokLb7zI+jShy1ke+4+T1Dqh763MoHTqtAvbaciJgy95d/liLymd6cFNXoyS2e1ANx5AnSuYL27vv12NsY0UXY11by341PQCx6OrX02TcGEviaaSyWxyizFpsqv3CO+jSBF+K5usHayk06NnrVuHBHVhsJd1ytvoci45mkAiC9SY4ZkoyMJ9kFD3XrFtlAsOv1vObewF2girWLOgyEpokgnoTjAVUUhw/6d80MLEkhWjl9FiTpP9yYpawY3WVZUIHPCZTc88NR+hBkQLEwju0YMzYoyogaACzqxsPpjEhGTQ2ssfF9kEzFqS3mYpnyFM3PDukd8Q2aHtQxcpyuwB8qYYUztM05lUsK6/aS5jV1SMkzPl9UdIVMLmT6R3aK4/TdMwvdXVrB52vE+ZxF3GhuBSPR58THOo0pk3l/sE9J+7mg=
