name: Pull Request Unit Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell-actions/setup@v2.8.0
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Run Unit Tests
        run: stack test --fast
